all: Ejercicio2 Ejercicio4 Ejercicio6a Ejercicio6b Ejercicio7libreria Ejercicio9 


Ejercicio2: Ejercicio2.c
	gcc -Wall -g Ejercicio2.c -o Ejercicio2
Ejercicio4: Ejercicio4.c
	gcc -Wall -g Ejercicio4.c -o Ejercicio4
Ejercicio6a: Ejercicio6a.c
	gcc -Wall -g Ejercicio6a.c -o Ejercicio6a
Ejercicio6b: Ejercicio6b.c
	gcc -Wall -g Ejercicio6b.c -o Ejercicio6b
Ejercicio7libreria: Ejercicio7libreria.c
	gcc -Wall -g semaforos.h semaforos.c Ejercicio7libreria.c -o Ejercicio7libreria
Ejercicio9: Ejercicio9.c
	gcc -Wall -g semaforos.h semaforos.c Ejercicio9.c -o Ejercicio9


clean:
	rm  Ejercicio2 Ejercicio4 Ejercicio6a Ejercicio6b Ejercicio7libreria Ejercicio9 
