
all: Ejercicio4a Ejercicio4b Ejercicio4moda Ejercicio4modb Ejercicio5a Ejercicio5b Ejercicio6 Ejercicio8 Ejercicio9 Ejercicio12a Ejercicio12b Ejercicio13 Ejercicio13mod


Ejercicio4a: Ejercicio4a.c
	gcc -Wall -g Ejercicio4a.c -o Ejercicio4a
Ejercicio4b: Ejercicio4b.c
	gcc -Wall -g Ejercicio4b.c -o Ejercicio4b
Ejercicio4moda: Ejercicio4moda.c
	gcc -Wall -g Ejercicio4moda.c -o Ejercicio4moda
Ejercicio4modb: Ejercicio4modb.c
	gcc -Wall -g Ejercicio4modb.c -o Ejercicio4modb
Ejercicio5a: Ejercicio5a.c
	gcc -Wall -g Ejercicio5a.c -o Ejercicio5a
Ejercicio5b: Ejercicio5b.c
	gcc -Wall -g Ejercicio5b.c -o Ejercicio5b
Ejercicio6: Ejercicio6.c
	gcc -Wall -g Ejercicio6.c -o Ejercicio6
Ejercicio8: Ejercicio8.c
	gcc -Wall -g Ejercicio8.c -o Ejercicio8
Ejercicio9: Ejercicio9.c
	gcc -Wall -g Ejercicio9.c -o Ejercicio9 -lm
Ejercicio12a: Ejercicio12a.c
	gcc -Wall -g Ejercicio12a.c -o Ejercicio12a -lpthread
Ejercicio12b: Ejercicio12b.c
	gcc -Wall -g Ejercicio12b.c -o Ejercicio12b -lpthread
Ejercicio13: Ejercicio13.c
	gcc -Wall -g Ejercicio13.c -o Ejercicio13 -lpthread
Ejercicio13mod: Ejercicio13mod.c
	gcc -Wall -g Ejercicio13mod.c -o Ejercicio13mod -lpthread


clean:
	rm  Ejercicio4a Ejercicio4b Ejercicio4moda Ejercicio4modb Ejercicio5a Ejercicio5b Ejercicio6 Ejercicio8 Ejercicio9 Ejercicio12a Ejercicio12b
